// Always override inherited application configuration; never use DATABASE_URL from a shell/.env.
Object.assign(process.env, {
  NODE_ENV: 'test',
  DATABASE_URL: 'postgres://unused:unused@127.0.0.1:1/monthloom_unit_test',
  SESSION_SECRET: 'monthloom-test-only-session-secret',
  SESSION_COOKIE_NAME: 'monthloom_test_session',
  SESSION_COOKIE_SECURE: 'false',
  SESSION_DURATION_HOURS: '168',
  API_PUBLIC_URL: 'http://localhost:4000',
  WEB_PUBLIC_URL: 'http://localhost:3000',
  CORS_ALLOWED_ORIGINS: 'http://localhost:3000',
  EMAIL_TRANSPORT: 'log',
  EMAIL_FROM_NAME: 'Monthloom Test',
  EMAIL_FROM_ADDRESS: 'test@example.com',
  EMAIL_REPLY_TO: '',
  RESEND_API_KEY: '',
  RESEND_ADMIN_KEY: '',
  LOG_LEVEL: 'silent',
  UPLOAD_DIR: 'unused-test-uploads',
  UPLOAD_MAX_SIZE_BYTES: '1024',
  UPLOAD_ALLOWED_MIME_TYPES: 'image/jpeg,image/png,image/webp',
  JSON_BODY_LIMIT: '1mb',
  RATE_LIMIT_MAX_REQUESTS: '10000',
  AUTH_RATE_LIMIT_MAX_REQUESTS: '1000',
  PASSWORD_RESET_RATE_LIMIT_MAX_REQUESTS: '1000',
  EMAIL_VERIFICATION_RATE_LIMIT_MAX_REQUESTS: '1000',
  TRUSTED_PROXY_HOPS: '0',
});
